server {
        listen 80;

        server_name bot.api.gotiger.dev;

        location / {
                return 301 https://$host$request_uri? ;
        }
}

server {
        listen 443 ssl;
        server_name bot.api.gotiger.dev;

        include /etc/nginx/conf.d/ssl-conf;
        include /etc/nginx/conf.d/options-ssl-nginx;
        include /etc/nginx/conf.d/block-bots;

        set $gotiger_bot_upstream "gotiger-bot-active:8020";

        location / {
            proxy_pass http://$gotiger_bot_upstream;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 86400;
        }
}
